-- Data awal. Jalankan SETELAH schema.sql
insert into spesies (nama,nama_latin,kategori,habitat,status,deskripsi,gambar,cari_foto) values
('Komodo','Varanus komodoensis','hewan','Pulau Komodo, Rinca, Flores (NTT)','Terancam Punah','Spesies kadal terbesar di dunia yang masih hidup. Hanya dapat ditemui di kepulauan Nusa Tenggara Timur.','',''),
('Harimau Sumatra','Panthera tigris sumatrae','hewan','Hutan hujan tropis Pulau Sumatra','Kritis','Subspesies harimau terakhir yang ada di Indonesia setelah harimau Jawa dan Bali dinyatakan punah.','',''),
('Orangutan Kalimantan','Pongo pygmaeus','hewan','Hutan dataran rendah Kalimantan','Kritis','Primata besar arboreal dengan rambut cokelat kemerahan yang memiliki tingkat kecerdasan tinggi.','',''),
('Rafflesia Arnoldii','Rafflesia arnoldii','tumbuhan','Hutan hujan Sumatra Selatan & Bengkulu','Langka','Bunga raksasa tanpa daun dan batang yang mengeluarkan aroma menyengat saat mekar penuh.','',''),
('Bunga Bangkai Raksasa','Amorphophallus titanum','tumbuhan','Hutan tropis Sumatra','Rentan','Tumbuhan endemik Sumatra yang memiliki perbungaan tidak bercabang terbesar di dunia.','',''),
('Burung Cendrawasih','Paradisaeidae','hewan','Hutan hujan daratan Papua','Dilindungi','Burung khas Papua yang terkenal akan keindahan bulu jantannya untuk ritual memikat betina.','',''),
('Anoa Dataran Rendah','Bubalus depressicornis','hewan','Hutan hujan Sulawesi','Terancam Punah','Kerbau kerdil endemik Sulawesi yang hidup secara soliter di hutan lebat.','',''),
('Kantong Semar','Nepenthes rajah','tumbuhan','Pegunungan Kalimantan','Dilindungi','Tumbuhan karnivora unik yang memanfaatkan perangkap berupa kantong berisi cairan pencerna.','',''),
('Anggrek Hitam','Coelogyne pandurata','tumbuhan','Cagar Alam Kersik Luway, Kalimantan Timur','Langka','Anggrek beraroma harum lembut dengan lidah bunga berwarna hitam pekat yang khas.','',''),
('Badak Jawa','Rhinoceros sondaicus','hewan','Taman Nasional Ujung Kulon, Banten','Kritis','Mamalia besar paling langka di bumi yang memiliki satu cula.','',''),
('Gajah Sumatra','Elephas maximus sumatranus','hewan','Hutan dataran rendah Sumatra','Kritis','Subspesies gajah Asia yang hanya hidup di Pulau Sumatra; populasinya menyusut akibat hilangnya hutan dan konflik dengan manusia.','',''),
('Badak Sumatra','Dicerorhinus sumatrensis','hewan','Hutan hujan Sumatra dan Kalimantan','Kritis','Badak terkecil di dunia, bercula dua dan bertubuh berambut; jumlahnya sangat sedikit di alam liar.','',''),
('Tapir Asia','Tapirus indicus','hewan','Hutan hujan Sumatra','Terancam Punah','Mamalia belang hitam-putih dengan belalai pendek yang lentur, aktif terutama pada malam hari.','',''),
('Beruang Madu','Helarctos malayanus','hewan','Hutan Sumatra dan Kalimantan','Rentan','Beruang terkecil di dunia dengan bercak berbentuk U di dada dan lidah panjang untuk mengambil madu.','',''),
('Macan Dahan Sunda','Neofelis diardi','hewan','Hutan Sumatra dan Kalimantan','Rentan','Kucing besar pemanjat pohon ulung dengan corak seperti awan pada bulunya.','',''),
('Kucing Emas Asia','Catopuma temminckii','hewan','Hutan Sumatra','Dilindungi','Kucing liar berbulu cokelat keemasan yang hidup soliter dan jarang terlihat.','',''),
('Macan Tutul Jawa','Panthera pardus melas','hewan','Hutan Pulau Jawa','Kritis','Subspesies macan tutul endemik Jawa yang kini menjadi predator puncak di pulau itu.','',''),
('Owa Jawa','Hylobates moloch','hewan','Hutan pegunungan Jawa Barat dan Tengah','Terancam Punah','Primata endemik Jawa yang bersuara nyaring dan hidup berpasangan.','',''),
('Siamang','Symphalangus syndactylus','hewan','Hutan Sumatra','Terancam Punah','Kera terbesar dari kelompok owa dengan kantung suara di tenggorokan.','',''),
('Bekantan','Nasalis larvatus','hewan','Hutan bakau dan rawa Kalimantan','Terancam Punah','Monyet berhidung panjang khas Kalimantan; jantan dewasa berhidung besar.','',''),
('Orangutan Sumatra','Pongo abelii','hewan','Hutan Aceh dan Sumatra Utara','Kritis','Kera besar berbulu oranye kemerahan yang hidup di bagian utara Pulau Sumatra.','',''),
('Orangutan Tapanuli','Pongo tapanuliensis','hewan','Ekosistem Batang Toru, Sumatra Utara','Kritis','Spesies orangutan yang baru dikenal secara ilmiah pada 2017 dengan populasi sangat kecil.','',''),
('Lutung Jawa','Trachypithecus auratus','hewan','Hutan Jawa, Bali, dan Lombok','Rentan','Monyet berbulu hitam atau keemasan yang hidup berkelompok di pepohonan.','',''),
('Surili Jawa','Presbytis comata','hewan','Hutan pegunungan Jawa Barat dan Tengah','Terancam Punah','Monyet pemakan daun endemik Jawa dengan jambul di kepala.','',''),
('Yaki','Macaca nigra','hewan','Hutan Sulawesi Utara','Kritis','Monyet hitam berjambul endemik Sulawesi Utara.','',''),
('Tarsius','Tarsius tarsier','hewan','Hutan Sulawesi','Rentan','Primata mungil bermata besar yang aktif pada malam hari.','',''),
('Kukang Jawa','Nycticebus javanicus','hewan','Hutan Pulau Jawa','Kritis','Primata nokturnal bermata besar yang bergerak lambat dan sering menjadi korban perdagangan satwa.','',''),
('Babirusa','Babyrousa babyrussa','hewan','Hutan Sulawesi dan Maluku','Rentan','Mamalia mirip babi dengan taring atas melengkung yang tumbuh menembus moncong.','',''),
('Dugong','Dugong dugon','hewan','Perairan pesisir dan padang lamun','Rentan','Mamalia laut pemakan lamun yang sering dikaitkan dengan legenda putri duyung.','',''),
('Banteng','Bos javanicus','hewan','Hutan Jawa dan Kalimantan','Terancam Punah','Sapi liar berwarna cokelat tua hingga hitam dengan bagian belakang kaki berwarna putih.','',''),
('Anoa Pegunungan','Bubalus quarlesi','hewan','Hutan pegunungan Sulawesi','Terancam Punah','Kerbau kerdil endemik Sulawesi yang lebih kecil daripada anoa dataran rendah.','',''),
('Rusa Bawean','Axis kuhlii','hewan','Pulau Bawean, Jawa Timur','Kritis','Rusa endemik Pulau Bawean dengan jumlah sangat terbatas.','',''),
('Kancil','Tragulus javanicus','hewan','Hutan Jawa dan Bali','Dilindungi','Hewan berkuku kecil yang terkenal sebagai tokoh cerdik dalam dongeng Nusantara.','',''),
('Kuskus Beruang','Ailurops ursinus','hewan','Hutan Sulawesi','Rentan','Marsupial pemanjat berekor pemegang yang bergerak lambat di pepohonan.','',''),
('Pesut Mahakam','Orcaella brevirostris','hewan','Sungai Mahakam, Kalimantan Timur','Kritis','Lumba-lumba berkepala bulat tanpa paruh panjang yang hidup di sungai.','',''),
('Trenggiling Sunda','Manis javanica','hewan','Hutan Sumatra, Jawa, dan Kalimantan','Kritis','Mamalia bersisik yang menggulung tubuh saat terancam dan sangat diburu secara ilegal.','',''),
('Kanguru Pohon Dingiso','Dendrolagus mbaiso','hewan','Pegunungan Papua','Terancam Punah','Kanguru pemanjat pohon berbulu hitam-putih endemik pegunungan Papua.','',''),
('Landak Semut Moncong Panjang Barat','Zaglossus bruijnii','hewan','Hutan pegunungan Papua','Kritis','Mamalia bertelur (monotremata) berduri dengan moncong panjang pemakan cacing tanah.','',''),
('Paus Biru','Balaenoptera musculus','hewan','Perairan laut dalam Indonesia','Terancam Punah','Hewan terbesar yang pernah hidup di bumi, melintasi perairan Nusantara.','',''),
('Cenderawasih Raja','Cicinnurus regius','hewan','Hutan Papua','Dilindungi','Cenderawasih kecil berwarna merah menyala dengan ekor berpilin.','',''),
('Kasuari Selatan','Casuarius casuarius','hewan','Hutan Papua','Dilindungi','Burung besar tak bisa terbang dengan kepala biru dan jambul tanduk di kepala.','',''),
('Elang Jawa','Nisaetus bartelsi','hewan','Hutan pegunungan Jawa','Terancam Punah','Burung pemangsa berjambul yang dianggap sebagai inspirasi lambang Garuda.','',''),
('Elang Bondol','Haliastur indus','hewan','Pesisir dan muara Indonesia','Dilindungi','Elang berkepala dan dada putih berbadan cokelat kemerahan, maskot Jakarta.','',''),
('Jalak Bali','Leucopsar rothschildi','hewan','Taman Nasional Bali Barat','Kritis','Burung berbulu putih dengan kulit biru di sekitar mata, endemik Bali.','',''),
('Maleo Senkawor','Macrocephalon maleo','hewan','Hutan Sulawesi','Terancam Punah','Burung endemik Sulawesi yang mengubur telurnya di tanah yang hangat.','',''),
('Rangkong Badak','Buceros rhinoceros','hewan','Hutan Sumatra, Kalimantan, dan Jawa','Rentan','Burung besar dengan tanduk berwarna jingga di atas paruhnya.','',''),
('Enggang Gading','Rhinoplax vigil','hewan','Hutan Sumatra dan Kalimantan','Kritis','Rangkong dengan balung kepala padat yang diburu untuk diperdagangkan.','',''),
('Kakatua Jambul Kuning','Cacatua sulphurea','hewan','Hutan Sulawesi dan Nusa Tenggara','Kritis','Kakatua putih berjambul kuning yang populasinya menurun akibat perdagangan.','',''),
('Kakatua Raja','Probosciger aterrimus','hewan','Hutan Papua dan Maluku','Dilindungi','Kakatua hitam besar berpipi merah dan berjambul.','',''),
('Nuri Raja Ambon','Alisterus amboinensis','hewan','Hutan Maluku dan Papua','Dilindungi','Burung nuri berbadan merah menyala dengan sayap hijau.','',''),
('Merak Hijau','Pavo muticus','hewan','Hutan Pulau Jawa','Terancam Punah','Burung dengan bulu ekor hias hijau keemasan yang dipamerkan jantan saat menarik betina.','',''),
('Julang Sulawesi','Rhyticeros cassidix','hewan','Hutan Sulawesi','Dilindungi','Burung rangkong berparuh besar endemik Sulawesi.','',''),
('Penyu Hijau','Chelonia mydas','hewan','Perairan pesisir Indonesia','Terancam Punah','Penyu laut pemakan lamun yang bertelur di pantai berpasir.','',''),
('Penyu Belimbing','Dermochelys coriacea','hewan','Laut dan pantai Indonesia','Rentan','Penyu terbesar di dunia dengan karapas kulit lunak berlunas.','',''),
('Penyu Sisik','Eretmochelys imbricata','hewan','Terumbu karang Indonesia','Kritis','Penyu berparuh runcing dengan sisik tempurung yang saling tumpang tindih.','',''),
('Buaya Senyulong','Tomistoma schlegelii','hewan','Rawa gambut Sumatra dan Kalimantan','Terancam Punah','Buaya berhidung sangat panjang dan ramping.','',''),
('Buaya Muara','Crocodylus porosus','hewan','Muara dan pesisir Indonesia','Dilindungi','Buaya terbesar yang masih hidup, mampu hidup di air payau dan laut.','',''),
('Arwana Super Red','Scleropages formosus','hewan','Sungai Kalimantan Barat','Terancam Punah','Ikan air tawar bersisik besar berkilau kemerahan yang bernilai tinggi.','',''),
('Coelacanth Indonesia','Latimeria menadoensis','hewan','Perairan Sulawesi Utara','Rentan','Ikan purba yang dijuluki fosil hidup, ditemukan di laut dalam dekat Manado.','',''),
('Hiu Paus','Rhincodon typus','hewan','Perairan Indonesia, termasuk Teluk Cenderawasih','Terancam Punah','Ikan terbesar di dunia, pemakan plankton yang jinak.','',''),
('Pari Manta','Mobula birostris','hewan','Perairan Komodo dan Raja Ampat','Rentan','Pari raksasa pemakan plankton dengan bentang sayap yang sangat lebar.','',''),
('Kupu-kupu Sayap Burung Rajah Brooke','Trogonoptera brookiana','hewan','Hutan Sumatra dan Kalimantan','Dilindungi','Kupu-kupu besar dengan bercak hijau metalik pada sayap hitam.','',''),
('Kepiting Kelapa','Birgus latro','hewan','Pulau-pulau kecil Indonesia','Rentan','Kepiting darat terbesar di dunia yang mampu memecahkan kelapa.','',''),
('Kima Raksasa','Tridacna gigas','hewan','Terumbu karang Indonesia','Rentan','Kerang terbesar di dunia yang hidup bersimbiosis dengan alga.','',''),
('Rafflesia Patma','Rafflesia patma','tumbuhan','Pangandaran dan Nusakambangan, Jawa','Dilindungi','Bunga parasit raksasa yang lebih kecil daripada Rafflesia arnoldii.','',''),
('Edelweis Jawa','Anaphalis javanica','tumbuhan','Pegunungan Jawa','Dilindungi','Bunga abadi yang tumbuh di ketinggian gunung dan dilindungi.','',''),
('Anggrek Bulan','Phalaenopsis amabilis','tumbuhan','Hutan Indonesia','Dilindungi','Anggrek berbunga putih besar yang ditetapkan sebagai puspa pesona.','',''),
('Anggrek Tebu','Grammatophyllum speciosum','tumbuhan','Hutan Asia Tenggara','Dilindungi','Anggrek terbesar di dunia dengan rumpun yang sangat besar.','',''),
('Anggrek Macan','Grammatophyllum scriptum','tumbuhan','Hutan Maluku dan Papua','Dilindungi','Anggrek berbunga belang cokelat kekuningan seperti kulit macan.','',''),
('Anggrek Larat','Dendrobium phalaenopsis','tumbuhan','Papua dan Maluku','Dilindungi','Anggrek berbunga ungu keunguan yang populer sebagai tanaman hias.','',''),
('Anggrek Kasut','Paphiopedilum glaucophyllum','tumbuhan','Hutan Pulau Jawa','Dilindungi','Anggrek berbibir kantong seperti sepatu.','',''),
('Kantong Semar Gentong','Nepenthes ampullaria','tumbuhan','Hutan Sumatra dan Kalimantan','Dilindungi','Kantong semar berkantong bulat kecil yang tumbuh bergerombol di tanah.','',''),
('Cendana','Santalum album','tumbuhan','Nusa Tenggara Timur','Rentan','Pohon beraroma harum yang kayunya dimanfaatkan untuk minyak dan kerajinan.','',''),
('Ulin','Eusideroxylon zwageri','tumbuhan','Hutan Sumatra dan Kalimantan','Rentan','Kayu besi yang sangat keras dan tahan air.','',''),
('Tengkawang','Shorea stenoptera','tumbuhan','Hutan Kalimantan','Terancam Punah','Pohon penghasil lemak nabati dari bijinya.','',''),
('Eboni Sulawesi','Diospyros celebica','tumbuhan','Hutan Sulawesi','Rentan','Pohon berkayu hitam bergaris yang bernilai tinggi.','',''),
('Gaharu','Aquilaria malaccensis','tumbuhan','Hutan Sumatra dan Kalimantan','Kritis','Pohon penghasil resin harum yang sangat mahal.','',''),
('Merbau','Intsia bijuga','tumbuhan','Hutan Papua','Rentan','Pohon kayu keras bernilai tinggi yang banyak ditebang.','',''),
('Palem Merah','Cyrtostachys renda','tumbuhan','Rawa Sumatra dan Kalimantan','Dilindungi','Palem hias berpelepah merah menyala.','',''),
('Rotan Manau','Calamus manan','tumbuhan','Hutan Sumatra','Terancam Punah','Rotan berdiameter besar untuk mebel; populasi alaminya menyusut.','',''),
('Damar','Agathis dammara','tumbuhan','Hutan Maluku dan Sulawesi','Rentan','Pohon konifer penghasil getah damar.','',''),
('Pasak Bumi','Eurycoma longifolia','tumbuhan','Hutan Sumatra dan Kalimantan','Dilindungi','Tanaman obat tradisional dengan akar yang berasa pahit.','',''),
('Api-api','Avicennia marina','tumbuhan','Pesisir Indonesia','Dilindungi','Pohon bakau pionir yang melindungi pantai dari abrasi.','',''),
('Bakau Merah','Rhizophora mucronata','tumbuhan','Hutan mangrove Indonesia','Dilindungi','Pohon bakau berakar tunjang yang menopang tegak di lumpur.','',''),
('Lamun Raksasa','Enhalus acoroides','tumbuhan','Padang lamun Indonesia','Dilindungi','Lamun besar yang menjadi pakan dugong dan penyu.','',''),
('Masoyi','Massoia aromatica','tumbuhan','Hutan Papua','Dilindungi','Pohon penghasil kulit kayu harum untuk obat dan minyak.','',''),
('Jamur Tiram','Pleurotus ostreatus','jamur','Kayu lapuk; dibudidayakan di seluruh Indonesia','Belum Dievaluasi','Jamur pangan berpayung seperti cangkang tiram yang banyak dibudidayakan pada media serbuk kayu.','',''),
('Jamur Merang','Volvariella volvacea','jamur','Jerami padi yang membusuk','Belum Dievaluasi','Jamur pangan yang tumbuh pada jerami padi dan populer dalam masakan Asia.','','Straw mushroom'),
('Jamur Kuping','Auricularia auricula-judae','jamur','Kayu lapuk di hutan tropis','Belum Dievaluasi','Jamur bertekstur kenyal menyerupai telinga yang banyak dipakai dalam masakan.','','Jamur kuping'),
('Jamur Lingzhi','Ganoderma lucidum','jamur','Kayu pohon berdaun lebar','Belum Dievaluasi','Jamur berkayu mengilap yang dimanfaatkan dalam pengobatan tradisional.','',''),
('Jamur Kelambu','Phallus indusiatus','jamur','Hutan tropis','Belum Dievaluasi','Jamur berkerudung jala putih yang dimanfaatkan sebagai pangan dan obat tradisional.','','Dictyophora indusiata'),
('Jamur Rayap','Termitomyces heimii','jamur','Tanah di sekitar sarang rayap','Belum Dievaluasi','Jamur yang tumbuh dari sarang rayap dan berpasangan dengan koloni rayap.','','Termitomyces'),
('Jamur Bercahaya','Mycena chlorophos','jamur','Hutan tropis lembap','Belum Dievaluasi','Jamur kecil yang memancarkan cahaya kehijauan dalam gelap (bioluminesensi).','','Bioluminescent fungus'),
('Ragi Tempe','Rhizopus oligosporus','jamur','Dibudidayakan; digunakan di Jawa','Belum Dievaluasi','Kapang yang mengubah kedelai menjadi tempe, makanan fermentasi khas Indonesia.','','Tempe'),
('Kapang Oncom','Neurospora intermedia','jamur','Jawa Barat','Belum Dievaluasi','Kapang berwarna oranye yang dipakai untuk membuat oncom, makanan fermentasi khas Sunda.','','Oncom'),
('Ragi Roti','Saccharomyces cerevisiae','jamur','Dibudidayakan','Belum Dievaluasi','Khamir bersel tunggal yang dipakai untuk roti, tape, dan minuman fermentasi.','','Ragi roti'),
('Angkak','Monascus purpureus','jamur','Dibudidayakan','Belum Dievaluasi','Kapang penghasil pigmen merah yang dipakai untuk pewarna dan fermentasi beras.','','Angkak'),
('Bakteri Nata','Komagataeibacter xylinus','mikroba','Dibudidayakan','Belum Dievaluasi','Bakteri penghasil selulosa yang dipakai untuk membuat nata de coco.','','Nata de coco'),
('Spirulina','Arthrospira platensis','mikroba','Perairan tawar beralkali; dibudidayakan','Belum Dievaluasi','Sianobakteri berwarna biru-hijau yang kaya protein dan dibudidayakan sebagai suplemen.','','Spirulina'),
('Chlorella','Chlorella vulgaris','mikroba','Perairan tawar','Belum Dievaluasi','Alga hijau bersel tunggal yang dibudidayakan untuk pakan dan suplemen.','','Chlorella'),
('Rhizobium','Rhizobium leguminosarum','mikroba','Bintil akar tanaman polong','Belum Dievaluasi','Bakteri yang hidup di bintil akar kacang-kacangan dan menambat nitrogen dari udara.','','Bintil akar'),
('Bakteri Asam Laktat','Lactiplantibacillus plantarum','mikroba','Makanan dan minuman fermentasi','Belum Dievaluasi','Bakteri yang berperan dalam fermentasi sayuran, susu, dan makanan tradisional.','','Lactobacillus'),
('Bacillus thuringiensis','Bacillus thuringiensis','mikroba','Tanah','Belum Dievaluasi','Bakteri tanah penghasil protein pembasmi serangga hama, dipakai sebagai biopestisida.','','Bacillus'),
('Zooxanthellae','Symbiodinium','mikroba','Terumbu karang Indonesia','Belum Dievaluasi','Alga bersel tunggal yang bersimbiosis dengan karang dan memberinya warna.','','Zooxanthellae'),
('Noctiluca','Noctiluca scintillans','mikroba','Perairan pesisir tropis','Belum Dievaluasi','Dinoflagelata laut bersel tunggal yang berpendar biru saat terusik.','','Sea sparkle')
on conflict (nama_latin) do nothing;
